server:
  port: 8761                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: localhost         # 指定该Eureka实例的主机名
    preferIpAddress: false
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 30000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
#spring:
#  mail:
#    #邮箱地址
#    host: ****.qq.com
#    #账号
#    username: 260146988@qq.com
#    #密码
#    password: ********
##    properties:
##      mail:
##        smtp:
##          auth: true
##          starttls:
##            enable: true
##            required: true
#
#
##    #默认端口
#    port: 25
#    #协议
#    protocol: smtp

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756